[template]
src   = "haproxy.cfg.tmpl"
dest  = "/usr/local/etc/haproxy/haproxy.cfg"
owner = "root"
mode  = "0644"
check_cmd  = "haproxy -c -f {{.src}}"
reload_cmd = "haproxy -f /usr/local/etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -D -sf $(cat /var/run/haproxy.pid)"
